### ISSUE TITLE
Catkin_make error

### ISSUE THREAD

**Issue by aecgabriel** [uuvsimulator/rexrov2#21]
After clone the directory to de src ROS directory to create a new workspace I'm having a problem. When I used the rexrov2 directory I didn't have any problem to create the ROS workspace.

####
[  0%] Built target geometry_msgs_generate_messages_cpp
[  0%] Built target geometry_msgs_generate_messages_eus
[  0%] Built target geometry_msgs_generate_messages_nodejs
[  0%] Built target std_msgs_generate_messages_py
[  0%] Built target std_msgs_generate_messages_nodejs
[  0%] Built target geometry_msgs_generate_messages_py
[  0%] Built target std_msgs_generate_messages_cpp
[  0%] Built target std_msgs_generate_messages_eus
[  0%] Built target std_msgs_generate_messages_lisp
[  0%] Built target geometry_msgs_generate_messages_lisp
[  0%] Built target uuv_control_cascaded_pid_gencfg
[  0%] Built target _uuv_auv_control_allocator_generate_messages_check_deps_AUVCommand
[  0%] Built target _uuv_control_msgs_generate_messages_check_deps_Hold
[  0%] Built target _uuv_control_msgs_generate_messages_check_deps_ClearWaypoints
[  0%] Built target _uuv_control_msgs_generate_messages_check_deps_WaypointSet
[  0%] Built target _uuv_control_msgs_generate_messages_check_deps_GetMBSMControllerParams
[  0%] Built target _uuv_control_msgs_generate_messages_check_deps_InitWaypointSet
[  0%] Built target _uuv_control_msgs_generate_messages_check_deps_GetSMControllerParams
[  0%] Built target _uuv_control_msgs_generate_messages_check_deps_Waypoint
[  0%] Built target _uuv_control_msgs_generate_messages_check_deps_SetSMControllerParams
[  0%] Built target _uuv_control_msgs_generate_messages_check_deps_StartTrajectory
[  0%] Built target _uuv_control_msgs_generate_messages_check_deps_SetMBSMControllerParams
[  0%] Built target _uuv_control_msgs_generate_messages_check_deps_GetPIDParams
[  0%] Built target _uuv_control_msgs_generate_messages_check_deps_SwitchToManual
[  0%] Built target _uuv_control_msgs_generate_messages_check_deps_Trajectory
[  0%] Built target _uuv_control_msgs_generate_messages_check_deps_GoTo
[  0%] Built target _uuv_control_msgs_generate_messages_check_deps_IsRunningTrajectory
[  0%] Built target _uuv_control_msgs_generate_messages_check_deps_GoToIncremental
[  0%] Built target _uuv_control_msgs_generate_messages_check_deps_ResetController
[  0%] Built target _uuv_control_msgs_generate_messages_check_deps_TrajectoryPoint
[  0%] Built target _uuv_control_msgs_generate_messages_check_deps_AddWaypoint
[  0%] Built target _uuv_control_msgs_generate_messages_check_deps_InitWaypointsFromFile
[  0%] Built target _uuv_control_msgs_generate_messages_check_deps_SwitchToAutomatic
[  0%] Built target _uuv_control_msgs_generate_messages_check_deps_GetWaypoints
make[2]: *** No rule to make target '/home/gabriel/catkin_ws/src/uuv_simulator/uuv_gazebo_plugins/uuv_gazebo_plugins/PROTOBUF_PROTOC_EXECUTABLE-NOTFOUND', needed by 'uuv_simulator/uuv_gazebo_plugins/uuv_gazebo_plugins/Accel.pb.cc'.  Stop.
CMakeFiles/Makefile2:4791: recipe for target 'uuv_simulator/uuv_gazebo_plugins/uuv_gazebo_plugins/CMakeFiles/uuv_gazebo_plugins_msgs.dir/all' failed
make[1]: *** [uuv_simulator/uuv_gazebo_plugins/uuv_gazebo_plugins/CMakeFiles/uuv_gazebo_plugins_msgs.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  0%] Built target uuv_descriptions_xacro_generated_to_devel_space_
[  0%] Built target _uuv_control_msgs_generate_messages_check_deps_SetPIDParams
[  0%] Built target _uuv_control_msgs_generate_messages_check_deps_InitCircularTrajectory
[  0%] Built target _catkin_empty_exported_target
[  1%] Built target uuv_dynamics
[  1%] Built target _uuv_control_msgs_generate_messages_check_deps_InitHelicalTrajectory
[  1%] Built target _uuv_control_msgs_generate_messages_check_deps_InitRectTrajectory
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j8 -l8" failed

**Comment by pzxz** [comment]
excuse me,would you mind telling me how you solve this problem?
I have meet the same error
